export const FETCH_POSTS_REQUEST = 'FETCH_POSTS_REQUEST'
export const FETCH_POSTS_SUCCESS = 'FETCH_POSTS_SUCCESS'
export const FETCH_POSTS_FAILURE = 'FETCH_POSTS_FAILURE'

export const FETCH_USERS_POST_REQUEST = 'FETCH_USERS_POST_REQUEST'
export const FETCH_USERS_POST_SUCCESS = 'FETCH_USERS_POST_SUCCESS'
export const FETCH_USERS_POST_FAILURE = 'FETCH_USERS_POST_FAILURE'

export const FETCH_USERS_COMMENT_REQUEST = 'FETCH_USERS_COMMENT_REQUEST'
export const FETCH_USERS_COMMENT_SUCCESS = 'FETCH_USERS_COMMENT_SUCCESS'
export const FETCH_USERS_COMMENT_FAILURE = 'FETCH_USERS_COMMENT_FAILURE'

export const FETCH_USERS_REQUEST = 'FETCH_USERS_POST_REQUEST'
export const FETCH_USERS_SUCCESS = 'FETCH_USERS_POST_SUCCESS'
export const FETCH_USERS_FAILURE = 'FETCH_USERS_POST_FAILURE'

export const FETCH_USERS_INFO_REQUEST = 'FETCH_USERS_INFO_REQUEST'
export const FETCH_USERS_INFO_SUCCESS = 'FETCH_USERS_INFO_SUCCESS'
export const FETCH_USERS_INFO_FAILURE = 'FETCH_USERS_INFO_FAILURE'

export const FETCH_ALBUMS_REQUEST = 'FETCH_ALBUMS_REQUEST'
export const FETCH_ALBUMS_SUCCESS = 'FETCH_ALBUMS_SUCCESS'
export const FETCH_ALBUMS_FAILURE = 'FETCH_ALBUMS_FAILURE'

export const FETCH_ALBUM_PHOTOS_REQUEST = 'FETCH_ALBUM_PHOTOS_REQUEST'
export const FETCH_ALBUM_PHOTOS_SUCCESS = 'FETCH_ALBUM_PHOTOS_SUCCESS'
export const FETCH_ALBUM_PHOTOS_FAILURE = 'FETCH_ALBUM_PHOTOS_FAILURE'
